### ISSUE TITLE
Different coloured boxes in boxplot

### ISSUE THREAD

**Issue by grero** [JuliaPlots/StatsMakie.jl#46]
Thanks for the package; it's proving really useful and I am happy that I can use my favourite way of comparing distributions, namely the box-and-whiskers plot : )
Is there currently a way to specify that each box should have a different colour?

**Comment by mkborregaard** [comment]
try something like `boxplot(Data(drivers), Group(color = :Year), :Year, :Deaths)`

**Comment by piever** [comment]
Thanks Michael, I was actually not aware that that would work :)

**Comment by grero** [comment]
Thanks! Recording for posterity, this is what I did (since I wanted to use plain arrays and not e.g. a DataFrame): 

```julia
using StatsMakie, Makie
a = repeat(1:5, inner = 20)
b = 1:100
p = boxplot(Group(color=a),a,b)
```

**Comment by grero** [comment]
Quick follow-up question: is there a way that I can control the colours used?

**Comment by mkborregaard** [comment]
Yeah can you pass a vector of colors to color? Otherwise maybe try passing a `Palette(vectorofcolors)`? Not completely sure how the theming interacts with the keyword args.

**Comment by mkborregaard** [comment]
Great. You can also pass the name of a colorbrewer color scheme, or set a theme, e.g. one of those in MakieThemes

**Comment by piever** [comment]
If the argument you pass to `color` (or any other attribute used in grouping) can be used as a palette (`AbstractArray` and `Function` are supported for now, I would like to add dictionary support as well), it gets used, otherwise the default in the palette is used. There are some docs at http://juliaplots.org/StatsMakie.jl/latest/ now, even though they are not complete.

**Comment by mkborregaard** [comment]
Great with Dict support! Palette also accepts a Symbol arg, Simon has the colorbrewer themes opened.
