### ISSUE TITLE
Warnings when using StatMakie

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaPlots/StatsMakie.jl#6]
I get the following warnings when using `Makie`, `StatMakie` and `StatsBase`:
```julia
[ Info: Precompiling StatMakie [0a7cab8b-0d7a-5c41-a0c5-90422634c308]
WARNING: using StatMakie.Histogram in module Main conflicts with an existing identifier.
julia> WARNING: both Makie and Base export "Text"; uses of it in module StatMakie must be qualified
WARNING: both Distributions and AbstractPlotting export "scale!"; uses of it in module StatMakie must be qualified
WARNING: both Makie and StatMakie export "scale!"; uses of it in module Main must be qualified
```

**Comment by piever** [comment]
The `Text` warning seems to be a `Makie` issue, similarly for `scale!`: while I understand that both Makie and Distributions want to export `scale!` (though it doesn't seem to conflict in terms of signatures) exporting `Text` that is already take by Base is a bit excessive, I'll open an issue in AbstractPloting.

Exporting `Histogram` instead is accidental and due to https://github.com/JuliaPlots/AbstractPlotting.jl/issues/15

**Comment by piever** [comment]
Actually I can close this one now as I've stopped reexporting Makie and exporting `Histogram` (which clashed with StatsBase)
